mod common;
use common::*;
fn main() {
    let mut runner = RsicvTestRunner::new();
    //ua-p-*
    runner.test(XLen::X64, "rv64ua-p-amoadd_d");
    runner.test(XLen::X64, "rv64ua-p-amoadd_w");
    runner.test(XLen::X64, "rv64ua-p-amoand_d");
    runner.test(XLen::X64, "rv64ua-p-amoand_w");
    runner.test(XLen::X64, "rv64ua-p-amomax_d");
    runner.test(XLen::X64, "rv64ua-p-amomax_w");
    runner.test(XLen::X64, "rv64ua-p-amomaxu_d");
    runner.test(XLen::X64, "rv64ua-p-amomaxu_w");
    runner.test(XLen::X64, "rv64ua-p-amomin_d");
    runner.test(XLen::X64, "rv64ua-p-amomin_w");
    runner.test(XLen::X64, "rv64ua-p-amominu_d");
    runner.test(XLen::X64, "rv64ua-p-amominu_w");
    runner.test(XLen::X64, "rv64ua-p-amoor_d");
    runner.test(XLen::X64, "rv64ua-p-amoor_w");
    runner.test(XLen::X64, "rv64ua-p-amoswap_d");
    runner.test(XLen::X64, "rv64ua-p-amoswap_w");
    runner.test(XLen::X64, "rv64ua-p-amoxor_d");
    runner.test(XLen::X64, "rv64ua-p-amoxor_w");
    runner.test(XLen::X64, "rv64ua-p-lrsc");

    runner.test(XLen::X32, "rv32ua-p-amoadd_w");
    runner.test(XLen::X32, "rv32ua-p-amoand_w");
    runner.test(XLen::X32, "rv32ua-p-amomax_w");
    runner.test(XLen::X32, "rv32ua-p-amomaxu_w");
    runner.test(XLen::X32, "rv32ua-p-amomin_w");
    runner.test(XLen::X32, "rv32ua-p-amominu_w");
    runner.test(XLen::X32, "rv32ua-p-amoor_w");
    runner.test(XLen::X32, "rv32ua-p-amoswap_w");
    runner.test(XLen::X32, "rv32ua-p-amoxor_w");
    runner.test(XLen::X32, "rv32ua-p-lrsc");

    //*-pm-*
    runner.test_mp(XLen::X64, "rv64ui-pm-add", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-addi", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-addiw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-addw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-and", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-andi", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-auipc", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-beq", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-bge", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-bgeu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-blt", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-bltu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-bne", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-fence_i", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-jal", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-jalr", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lb", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lbu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-ld", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lh", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lhu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lui", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-lwu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-or", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-ori", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sb", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sd", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sh", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-simple", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sll", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-slli", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-slliw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sllw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-slt", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-slti", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sltiu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sltu", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sra", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-srai", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sraiw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sraw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-srl", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-srli", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-srliw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-srlw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-sub", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-subw", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-xor", 2);
    runner.test_mp(XLen::X64, "rv64ui-pm-xori", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-add", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-addi", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-and", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-andi", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-auipc", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-beq", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-bge", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-bgeu", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-blt", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-bltu", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-bne", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-fence_i", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-jal", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-jalr", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-lb", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-lbu", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-lh", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-lhu", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-lui", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-lw", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-or", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-ori", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sb", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sh", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-simple", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sll", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-slli", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-slt", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-slti", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sltiu", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sltu", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sra", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-srai", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-srl", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-srli", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sub", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-sw", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-xor", 2);
    runner.test_mp(XLen::X32, "rv32ui-pm-xori", 2);

    runner.test_mp(XLen::X64, "rv64ua-pm-lrsc", 4);
    runner.test_mp(XLen::X32, "rv32ua-pm-lrsc", 4);
}
